### ISSUE TITLE
System.DllNotFoundException: 'Unable to load DLL 'python37' or one of its dependencies: T

### ISSUE THREAD

**Issue by dewynternet101** [SciSharp/Keras.NET#101]
Hi,

for days I've been trying to get this running with no luck.  I've followed the instructions, tried installing keras.net from nuget, installing python, installing the dependencies but no luck.  I get the same issue when trying to run the source code directly too.

I either get the error above or if I play about setting the paths in my code I get passed that error and then have another error telling me it can't find numpy.

I've tried removing/reinstalling.  I've tried 3 different machines.  I've tried with standard python download as well as anaconda.

I have successfully built a model on the machine in anaconda using keras/tensorflow so I know for a fact that it works in Python.  It's just that any attempt to initialise any Python from dot.net fails.

Any help appreciated.  As I say it all works in anaconda directly, just trying to call it from dot net fails.   It's one error after another.  

example errors:

System.DllNotFoundException: Unable to load DLL 'python37': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
   at Python.Runtime.Runtime.Py_IsInitialized()
   at Python.Runtime.Runtime.Initialize(Boolean initSigs)
   at Python.Runtime.PythonEngine.Initialize(IEnumerable`1 args, Boolean setSysArgv, Boolean initSigs)
   at Numpy.np.InstallAndImport(Boolean force)
   at Numpy.np.<>c.<.cctor>b__599_0()
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.LazyInitValue()
   at Numpy.np.get_float64()
   at Numpy.np.array[T](T[,] object, Dtype dtype, Nullable`1 copy, String order, Nullable`1 subok, Nullable`1 ndmin)
   at Keras.Net.Program.Main(String[] args) in C:\Users\c\source\repos\Keras.Net\Keras.Net\Program.cs:line 83

**OR IF I SET PYTHON PATHS IN CODE I THEN GET THIS ERROR**

I know for a fact numpy is installed as it works from Python directly!!!

Python.Runtime.PythonException: ModuleNotFoundError : No module named 'numpy'
   at Python.Runtime.Runtime.CheckExceptionOccurred()
   at Python.Runtime.PythonEngine.ImportModule(String name)
   at Numpy.np.InstallAndImport(Boolean force)
   at Numpy.np.<>c.<.cctor>b__599_0()
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.LazyInitValue()
   at Numpy.np.get_float64()
   at Numpy.np.array[T](T[,] object, Dtype dtype, Nullable`1 copy, String order, Nullable`1 subok, Nullable`1 ndmin)
   at Keras.Net.Program.Main(String[] args) in C:\Users\c\source\repos\Keras.Net\Keras.Net\Program.cs:line 83

Any help appreciated, many thanks!

**Comment by Trippley** [comment]
Copy the python37.dll to your programm folder from
`C:\Users\%user%\AppData\Local\Programs\Python\Python37`

That environment should have numpy and keras installed via pip.

**Comment by dewynternet101** [comment]
Thanks but it's already there.  No joy.

Should I be setting any specific paths/variables?

**Comment by dewynternet101** [comment]
Progress but now I get this


Using TensorFlow backend.
Using TensorFlow backend.
Using TensorFlow backend.
Using TensorFlow backend.
Python.Runtime.PythonException: ImportError : Traceback (most recent call last):
  File "C:\Users\C\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow_core\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\C\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\C\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "C:\Users\C\AppData\Local\Programs\Python\Python37\lib\imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Users\C\AppData\Local\Programs\Python\Python37\lib\imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: The specified module could not be found.

**Comment by deepakkumar1984** [comment]
Is the issue solved?

**Comment by deepakkumar1984** [comment]
Closing as there is no further comments. Please open another issue if still facing it.

**Comment by qzjake** [comment]
> 7.dll to your programm folder from
> `C:\Users\%user%\AppData\Local\Programs\Python\Python37`

Make sure the python.dll location is in your environment path
