### ISSUE TITLE
Python.Runtime.PythonException: ImportError : Keras requires TensorFlow 2.2 or higher. Install TensorFlow via `pip install tensorflow`

### ISSUE THREAD

**Issue by abualfateh** [SciSharp/Keras.NET#156]
Hi,
I already install both Keras and TensorFlow but still get below error:

Python.Runtime.PythonException: ImportError : Keras requires TensorFlow 2.2 or higher. Install TensorFlow via `pip install tensorflow`
   at Python.Runtime.Runtime.CheckExceptionOccurred()
   at Python.Runtime.PythonEngine.ImportModule(String name)
   at Keras.Keras.InstallAndImport(String module)
   at Keras.Keras.<>c.<.cctor>b__27_0()
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.LazyInitValue()
   at Keras.Models.Sequential..ctor()
   at TechApp.ComML.ViewModels.TrainingTestingViewModel.DNN(Int32 ModelRunId) in

**Comment by Nodice** [comment]
You may have multiple versions python versions installed or you are using many .net python engines running in .net. I was testing Python.Included and it was messing up my Keras.NET. Try uninstalling Keras.NET and all of the other projects it installs and reinstall it. This fixed it for me.
