### ISSUE TITLE
PythonException: AttributeError when depolying with ClickOnce

### ISSUE THREAD

**Issue by Xandolph** [SciSharp/Keras.NET#49]
Hi! 
My application works perfectly in Visual Studio. [EDIT]: It's a Windows Forms Application.
As soon as I deploy it with ClickOnce and run it, I get the following error when calling a Keras Function for the first time (in this case it's Keras.Utils.Util.ToCategorical):

************** Exception Text **************
Python.Runtime.PythonException: AttributeError : 'NoneType' object has no attribute 'write'
   at Python.Runtime.Runtime.CheckExceptionOccurred()
   at Python.Runtime.PythonEngine.ImportModule(String name)
   at Keras.Keras.InstallAndImport(String module)
   at Keras.Keras.<>c.<.cctor>b__18_0()
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.LazyInitValue()
   at Keras.Utils.Util.ToCategorical(NDarray y, Nullable`1 num_classes, String dtype)
   at Reifprognose.KerasTest.btnStart_Click(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

Please help!

Thanks a lot!

**Comment by deepakkumar1984** [comment]
Never tested with ClickOnce, Can you share me the click once package?

**Comment by Xandolph** [comment]
The problem is, that Keras wants to write to the console but when Applicartion Output type is set to "Windows Application" in Visual Studio there is no console and the error occurs.
I solved this by setting the output type to "Console Application" and then hide the consoel window.

**Comment by deepakkumar1984** [comment]
Cool.. thanks for sharing the solution. Closing the issue now.
